language: java
dist: trusty
sudo: false
addons:
  chrome: stable      
jdk:
  - oraclejdk8
script:
  - mvn -B clean package
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'