language: java
dist: trusty
sudo: false
addons:
  sonarcloud
  chrome: stable      
jdk:
  - oraclejdk8
script:
  - mvn -B clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.organisation=$SONAR_ORGANISATION
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'